### ISSUE TITLE
Complete noob, can't seem to make it work

### ISSUE THREAD

**Issue by kozmo47** [bonnici/node-steam-trash-bot#5]
So, apparently i installed Node.Js.
When i try to use npm install i get:
C:\Users\KGB\Downloads\node-steam-trash-bot-master\node-steam-trash-bot-master>n
pm install
npm WARN package.json argv@0.0.2 No repository field.
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/seishun/node-steam-trade.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/seishun/node-steam-trade.git) undefined
npm ERR! git clone git://github.com/seishun/node-steam-trade.git undefined
npm ERR! git clone git://github.com/seishun/node-steam-trade.git undefined
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\KGB\Downloads\node-steam-trash-bot-master\node-steam-trash
-bot-master
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ENOGIT
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\KGB\Downloads\node-steam-trash-bot-master\node-steam-trash
-bot-master\npm-debug.log
npm ERR! not ok code 0

I tried npm install git, i get:
npm WARN package.json argv@0.0.2 No repository field.
git@0.1.5 node_modules\git
└── mime@1.2.9

And then i get the same error as above when i am trying to just use npm install.

I did programming around 8 years ago, but not much, and i am completely lost. I'd appreciate some help.

**Comment by eknowles** [comment]
If you read the error it says..
```
npm ERR! git clone git://github.com/seishun/node-steam-trade.git undefined
npm ERR! not found: git
```
Are you sure you have the GIT cli installed?

http://git-scm.com/download/win

**Comment by kozmo47** [comment]
Thanks for the quick reponse, but i still can't make it work, i don't know, beats me so hard.
F:\bot\node-steam-trash-bot>npm install
npm WARN package.json argv@0.0.2 No repository field.
npm WARN package.json steam-trade@0.2.4 No repository field.
-


> ursa@0.8.1 install F:\bot\node-steam-trash-bot\node_modules\steam\node_modules
\ursa
> node-gyp configure && node-gyp build && node install.js

|
F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\ursa>node "C:\Users\
KGB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\no
de-gyp\bin\node-gyp.js" configure
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\KGB\AppData\Roaming\npm\node_module
s\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Users\KGB\AppData\Roaming\npm\node_modules\npm\node_mod
ules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\KGB\\AppData\\Roaming\\npm\\node_modules\\np
m\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\ursa
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
-
> ref@1.0.0 install F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\
ref
> node-gyp rebuild


F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\ref>node "C:\Users\K
GB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\nod
e-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\KGB\AppData\Roaming\npm\node_module
s\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Users\KGB\AppData\Roaming\npm\node_modules\npm\node_mod
ules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\KGB\\AppData\\Roaming\\npm\\node_modules\\np
m\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\ref
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

> protobuf@0.11.0 install F:\bot\node-steam-trash-bot\node_modules\steam\node_mo
dules\protobuf
> node-gyp rebuild


F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\protobuf>node "C:\Us
ers\KGB\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Users\KGB\AppData\Roaming\npm\node_module
s\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Users\KGB\AppData\Roaming\npm\node_modules\npm\node_mod
ules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at Object.oncomplete (evalmachine.<anonymous>:108:15)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\KGB\\AppData\\Roaming\\npm\\node_modules\\np
m\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\bot\node-steam-trash-bot\node_modules\steam\node_modules\protobu
f
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "node" "C:\\Users\\KGB\\AppData\\Roaming\\npm\\node_modules\\npm\\
bin\\npm-cli.js" "install"
npm ERR! node v0.10.36
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE

npm ERR! ursa@0.8.1 install: `node-gyp configure && node-gyp build && node insta
ll.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ursa@0.8.1 install script 'node-gyp configure && node-gyp
 build && node install.js'.
npm ERR! This is most likely a problem with the ursa package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && node-gyp build && node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ursa
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\bot\node-steam-trash-bot\npm-debug.log



-

I have python installed for what matters.

**Comment by eknowles** [comment]
I think this issue can be closed.

This is to do with https://github.com/seishun/node-steam 

```
Windows note: this module depends on ursa. Follow its installation prerequisites first.
```

Read this FULLY. https://github.com/NodePrime/ursa

**Comment by kozmo47** [comment]
Ursa can't be installed, i get the error above.
Anyway, sorry for taking your time away.

**Comment by bonnici** [comment]
I remember having trouble with installation on Windows, some notes from https://github.com/bonnici/node-steam-chat-bot might help: 

To get this running in Windows you'll need to follow the setup instructions for [node-gyp](https://github.com/TooTallNate/node-gyp#installation)  and also use a branch of libxmljs as described in [this issue](https://github.com/polotek/libxmljs/issues/176) (TLDR is to run 'npm install polotek/libxmljs#vendor-src' before 'npm install').
